AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Parameters:
  FullWebsiteDomainName:
    Type: String
    Description: e.g. pgaimpact.org or impact.sandboxpga.org. DO NOT add www.
  Route53HostedZoneId:
    Type: "AWS::Route53::HostedZone::Id"
    Description: Hosted Zone Id of the domain

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Domain"
        Parameters: 
          - FullWebsiteDomainName
          - Route53HostedZoneId
    ParameterLabels:
      FullWebsiteDomainName: 
        default: "Full Domain Name"
      Route53HostedZoneId: 
        default: "Hosted Zone ID"

Resources:
              
  DNSNameForWebsite:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      RecordSets:
      - 
        Name: !Ref FullWebsiteDomainName
        Type: A # IPv4 Record
        Value: '23.185.0.3'
      - 
        Name: !Ref FullWebsiteDomainName
        Type: AAAA # IPv6 Record
        Value: '2620:12a:8000::3'
      - 
        Name: !Ref FullWebsiteDomainName
        Type: AAAA # IPv6 Record
        Value: '2620:12a:8001::3'

  DNSNameForWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: www.pgaimpact.org
      Type: CNAME
      HostedZoneId: !Ref Route53HostedZoneId
      ResourceRecords:
      - pgaimpact.org
      TTL: 300

Outputs:
  WebsiteURL:
    Value: !Join ['', ['https://', !Ref FullWebsiteDomainName]]
    Description: The URL of the newly created website
