AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Parameters:
  FullWebsiteDomainName:
    Type: String
    Description: e.g. pgaimpact.org or impact.sandboxpga.org. DO NOT add www.
  CreateWWW: 
    Type: String
    Description: e.g. www.pgaimpact.org. Do not use if main website uses a subdomain. Wildcard SSL cert won't be valid for www.impact.sandboxpga.org
    AllowedValues: [true, false]
    Default: true
  Route53HostedZoneId:
    Type: "AWS::Route53::HostedZone::Id"
    Description: Hosted Zone Id of the domain
      
Conditions: 
  CreateWWWRedirect: !Equals [ !Ref CreateWWW, true ]

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Domain"
        Parameters: 
          - FullWebsiteDomainName
          - CreateWWW
          - Route53HostedZoneId
    ParameterLabels:
      FullWebsiteDomainName: 
        default: "Full Domain Name"
      CreateWWW: 
        default: "Auto-create www Redirect"
      Route53HostedZoneId: 
        default: "Hosted Zone ID"
      AcmCertificateArn: 
        default: "ACM SSL Certificate ARN"
      CloudfrontDefaultTTL: 
        default: "Default Cache TTL"

Resources:
              
  DNSNameForWebsite:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref Route53HostedZoneId
      RecordSets:
      - 
        Name: !Ref FullWebsiteDomainName
        Type: A # IPv4 Record
        Value: '23.185.0.3'
      - 
        Name: !Ref FullWebsiteDomainName
        Type: AAAA # IPv6 Record
        Value: '2620:12a:8000::3'
      - 
        Name: !Ref FullWebsiteDomainName
        Type: AAAA # IPv6 Record
        Value: '2620:12a:8001::3'

  DNSNameForWWW:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: www.pgaimpact.org
      Type: CNAME
      HostedZoneId: !Ref Route53HostedZoneId
      ResourceRecords:
      - pgaimpact.org
      TTL: 300

Outputs:
  WebsiteURL:
    Value: !Join ['', ['https://', !Ref FullWebsiteDomainName]]
    Description: The URL of the newly created website
